version: "2.2"

services:
  alpine:
    build:
      context: .
      dockerfile: Dockerfile
      labels:
        org.opencontainers.image.authors: Yourself
        org.opencontainers.image.vendor: "Your organisation"
      network: host
      args:
        - TEST=test
        - "TEST2=gnurf"
    image: efrecon/myalpine
  enipla:
    build: .
    image: efrecon/enipla
