name: Simplistic Test

on:
  # On all push
  push:

jobs:
  test:
    runs-on: ubuntu-latest

    name: Test the Example

    steps:
      -
        name: Checkout Code
        uses: actions/checkout@v2
      -
        name: Test
        uses: .
        with:
          tags: "test latest"
          age: "0"
          init: ./example/init.d
          cleanup: ./example/cleanup.d
